import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>Joe Test</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/joe-test',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/joe-test',
  footer: {
    text: 'Joe Test - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – Joe Test'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Joe Test" />
      <meta property="og:description" content="Documentation for Joe Test" />
    </>
  )
}

export default config
